#! /usr/bin/env python3
from optparse import OptionParser

def generateAliases(card,drive,addr,bay):
    print("CARD: ", card)
    print("DRIVE: ", drive)
    print("ADDR: ", addr)
    print("BAY: ", bay)
    
    alias24i = {
        "ssd":[2,3,1,0,6,7,5,4,18,19,17,16,22,23,21,20,10,11,9,8,14,15,13,12]
    }
    
    alias16i = {
        "ssd": [2,3,1,0,6,7,5,4,18,19,17,16,22,23,21,20],
        "hdd": [2,3,1,0,6,7,5,4,18,19,17,16,22,23,21]
    }
    
    alias16i9405W = {
        "ssd": [9,11,13,15,8,10,12,14,1,3,5,7,0,2,4,6]
    }
    
    conf_file = open("vdev_id.conf","a")
    
    if card == "24i":
        drive_number = 1
        for phy in alias24i[drive]:
            line = "alias {b}-{dn}\t/dev/disk/by-path/pci-0000:{a}:00.0-sas-phy{p}-lun-0\n".format(b=bay,dn=drive_number,a=addr,p=phy)
            drive_number += 1
            conf_file.write(line)
    
    elif card == "16i":
        drive_number = 1
        for phy in alias16i[drive]:
            line = "alias {b}-{dn}\t/dev/disk/by-path/pci-0000:{a}:00.0-sas-phy{p}-lun-0\n".format(b=bay,dn=drive_number,a=addr,p=phy)
            drive_number += 1
            conf_file.write(line)
            
    elif card == "16i9405W":
        drive_number = 0
        for phy in alias16i9405W[drive]:
            line = "alias {b}-{dn}\t/dev/disk/by-path/pci-0000:{a}:00.0-sas-phy{p}-lun-0\n".format(b=bay,dn=drive_number,a=addr,p=phy)
            drive_number += 1
            conf_file.write(line)
    conf_file.close()
    
    
def main():
    parser = OptionParser()
    parser.add_option("-c","--card",action="store",dest="card",default=None,help="Specify which card type 24i or 16i")
    parser.add_option("-d","--drive",action="store",dest="drive",default=None,help="Specify which drive types are connected")
    parser.add_option("-a","--addr",action="store",dest="addr",default=None,help="Specify which bus address to use")
    parser.add_option("-b","--bay",action="store",dest="bay",default=None,help="Specify which bay to start with")
    (options,args) = parser.parse_args()
    
    card = None
    drive = None
    bay = None
    addr = None
    
    if not (options.card and options.drive and options.addr and options.bay):
        print("must provide -c, -d, -a, and -b options")
        exit()
    
    if not (options.card == "24i" or options.card == "16i" or options.card == "16i9405W"):
        print("card option invalid")
        exit()
    
    if not (options.drive == "ssd" or options.drive == "hdd"):
        print("drive option invalid")
        exit()
    
    if options.drive == "hdd" and options.card == "24i":
        print("24i and hdd should not be paired")
        exit()
    
    card = str(options.card)	
    drive = str(options.drive)
    addr = str(options.addr)
    bay = str(options.bay)
    
    if card and drive and addr and str(bay).isnumeric():
        generateAliases(card,drive,addr,bay)
    
    
if __name__ == "__main__":
    main()