#!/usr/bin/bash
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=12 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4:/dev/1-3:/dev/1-5:/dev/1-6:/dev/1-7:/dev/1-8:/dev/1-9:/dev/1-10:/dev/1-11:/dev/1-12
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=16 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4:/dev/1-3:/dev/1-5:/dev/1-6:/dev/1-7:/dev/1-8:/dev/1-9:/dev/1-10:/dev/1-11:/dev/1-12:/dev/1-13:/dev/1-14:/dev/1-15:/dev/1-16
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=3 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=8 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4:/dev/1-3:/dev/1-5:/dev/1-6:/dev/1-7:/dev/1-8
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=4 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-3:/dev/1-4
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=6 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4:/dev/1-3:/dev/1-5:/dev/1-6
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=9 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-4:/dev/1-3:/dev/1-5:/dev/1-6:/dev/1-7:/dev/1-8:/dev/1-9:/dev/1-10:/dev/1-11:/dev/1-12
echo 3 > /proc/sys/vm/drop_caches 
fio --name=name --output=13 --filesize=4g --bs=1M --ioengine=libaio --readwrite=read --numjobs=1 --filename=/dev/1-1:/dev/1-2:/dev/1-3:/dev/1-5:/dev/1-6:/dev/1-7:/dev/1-9:/dev/1-10:/dev/1-11:/dev/1-13:/dev/1-14:/dev/1-15

